### ISSUE TITLE
[IPH] Individual Registration

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#1]
Create Subject type: Individual
Name of Subject: Individual
Form Requirements:
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=1346893247

**Comment by AchalaBelokar** [comment]
Year of education  is not more than age

**Comment by utkarshavni** [comment]
- [ ] Occupation is not displayed when Age is equal to 7 years.

**Comment by Gojo-Taqi** [comment]
As discussed with utkarsh, if the individual is exactly 7 years of age, the validation will not work.
But if the individual is 7 years and 1 day or greater, the validation works fine
