### ISSUE TITLE
[IPH] Child enrollment and exit

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#12]
Once consent of mother is given for collecting details, mother and child are enrolled in programs. Child will be enrolled into child program.
- [x] Create a program called Child.
- [x] Enrollment eligibility - Child (individual) whose age is below 1 month should only be eligible for enrollment. Child ageing one month or older than that should not have Child program button visible.
- [x] Enrollment form requirements:
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=13319505

Child exit from program:

- [x] Exit form requirements:
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=912235014

**Comment by AchalaBelokar** [comment]
- [x] the Hututu Hututu individual more than one month still child enrol is visible .

- [x] Caesarean Indication is multi-select currently it is showing single select.

**Comment by AchalaBelokar** [comment]
- [x] Validation need to required for child validation.

- [x] Resuscitation needs to required Multiple select.
