### ISSUE TITLE
[IPH] Collect blood sample for Individual

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#14]
- [x] Create a general encounter named "Collect blood sample details" against the Subject Individual.
- [x] Encounter eligibility - For only 18 years and above and those who do not have LMP question answered.
- [x] This visit will be scheduled on the same date as registration and overdue will be after two weeks.
- [x] Further scheduling will happen as given below:
- 2nd visit - 12 months after Registration.
- 3rd visit - 2 years after Registration. This will be the last scheduling.
- [x] Form requirements:
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=651233342   
- If Individual has answered "Have you used or currently use any kind of substance" as Yes then show all options and if No then only show Hemoglobin in collect blood sample question.

**Comment by utkarshavni** [comment]
Moving this card to Ready - have updated changes in details above, unticked those specific tasks.  @Gojo-Taqi @AchalaBelokar

**Comment by AchalaBelokar** [comment]
- [ ] 2nd visit - 12 months after Registration.
     

- [ ] 3rd visit - 2 years after Registration

not showing the visit scheduling

**Comment by AchalaBelokar** [comment]
- [ ] after editing the reg it is generating another collect blood sample.

**Comment by Gojo-Taqi** [comment]
- [x] Remove underscores from the individual identifier
