### ISSUE TITLE
[IPH] Misc changes 

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#22]
- [x] In Household registration, for Household ID field, it should generate a unique identifier for the household in the following format:
tal_vila_date_timestamp  (where tal = first three letters of the block, vila = first three letters of the village)
- [x] For Individual, generate unique identifier for the Individual ID field, in following format:
combination of non-repeat 3 alphabet and non-repeat 3 number  - i.e. abc146
- [x] Input value range for following values in Individual anthropometry
Spirometry FVC = 25% to 150 %
Spirometry FEV1/FVC= 0 to 1
- [x] While cancelling a visit for Individual, Child or Mother add following fields:
"Reason for cancellation" - Not available at the time of visit, Household member opposed, Not interested in current visit, Either child or mother unwell
- [x] Option Either child or mother unwell to be only shown in cancellation encounters of Mother and Child 
- [x] Add following options in Reason for exit while user exits individual from the program
1. Not interested
2. Migrated to non-study area.
3.  Child death 
4.  Mother death
5.  Either child or mother unwell

**Comment by Gojo-Taqi** [comment]
For the first point, the id is been set with this format
vil_date_time
vil = First three characters of the village (lowest address level)
date = Today's date without hyphen (-)
time = hour:minute:seconds


For the second point, the identifier source format is
vil_indentifier_source
vil = first 3 characters of the village (lowest address level)
identifier_source = Individual id identifier source

**Comment by AchalaBelokar** [comment]
- [x] For Individual, generate unique identifier for the Individual ID field, in following format:
combination of non-repeat 3 alphabet and non-repeat 3 number - i.e. abc146
after entering the mobile no individual id is showing like this.
![Screenshot 2023-02-22 at 6.46.02 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/41cb4d87-5971-45b2-b67b-07bc3f8c9cf6)

**Comment by AchalaBelokar** [comment]
- [ ]  Input value range for following values in Individual anthropometry
Spirometry FVC = 25% to 150 %
Spirometry FEV1/FVC= 0 to 1  not clear the

**Comment by AchalaBelokar** [comment]
- [ ]  Input value range for following values in Individual anthropometry
Spirometry FVC = 25% to 150 %
Spirometry FEV1/FVC= 0 to 1  not clear the

**Comment by AchalaBelokar** [comment]
- [ ]  Input value range for following values in Individual anthropometry
Spirometry FVC = 25% to 150 %
Spirometry FEV1/FVC= 0 to 1  not clear the

**Comment by AchalaBelokar** [comment]
- [x]  Input value range for following values in Individual anthropometry
Spirometry FVC = 25% to 150 %
Spirometry FEV1/FVC= 0 to 1  not appearing for individual

**Comment by Gojo-Taqi** [comment]
For individual it doesn't appear because there is a chance that the individual can be a father or a child, and both of them have different values.
Hence the two fields don't have any ranges or any absolute values

**Comment by AchalaBelokar** [comment]
- [x] After filling the household the summary is showing  voided hh id ![Screenshot 2023-02-24 at 11.18.39 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/51b70185-aa13-43af-9dc2-7dcd2fbcfe6c)

**Comment by utkarshavni** [comment]
- [x] Household ID value changes when answer is provided in another question on the page.

**Comment by AchalaBelokar** [comment]
- [x] when I am editing the user HHiD is changed
