### ISSUE TITLE
[IPH] UAT Feedback

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#25]
**Organization: IPH CTRITH UAT**
- [x] Upload the IPH CTRITH bundle on the UAT org.
Once done, do the changes as mentioned below.
- [x] Keep following fields in Mother enrollment. They are not captured for pregnant woman  while registering so need to capture in enrollment.  Concepts are already there.
1. Years of education
2. Education
3. Occupation
- [x] Create a Program called Substance use.
- [x] Program Eligibility - All above 10 years should be eligible.
- [x] Create a Program encounter called "Record Substance use details". It should be scheduled on the same date as enrollment.
- [x] The program encounter for substance use will only be scheduled once.
- [x] Record Substance use details should be copy of the Substance use details encounter. All the rules should be as it is.
- [x] Remove the General Substance use details encounter as that is not needed.
- [x] Remove Substance use details encounter from Mother Program as well.
- [x] As done for Child Anthropometry details encounter where we are asking the details twice and then showing questions to show Average of both readings, same needs to be done for Mother Anthropometry encounter as well.
- [x] Keep Collect blood sample details encounter (General encounter) and remove blood sample collection encounter which is part of program.
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=651233342
- [x] Schedule the Collect blood sample details (General encounter) when Individual is enrolled in Substance use prgoram. Schedule it on the same date as of enrollment.
- [x] Schedule subsequent blood sample collection encounter after 3 month, 6 month, 12 month and 2 years from the first blood sample collection encounter.
- [x] Schedule collect blood sample results encounter 1 week after the blood sample is collected. Keep overdue date as 2 weeks.
- [x] Add a question in Mother enrolment form - "Please provide consent proof" with concept datatype as of image.

**Offline Dashboard Cards**:  (Make this default dashboard)
- [x] Count of women who are eligible to be enrolled into Mother program but enrollment has not happened.  (Title - Enrollment pending for mother program")
- [ ] Count of women enrolled in mother program but not mapped to household. (Title - Mothers not mapped to household)
- [x] Count of individuals for whom Blood sample collection encounter scheduled but not filled. (Title - Blood sample collection pending)
- [x] Count of women for whom Delivery encounter is scheduled but not submitted. (Title - Deliveries to be completed)
- [x] Count of individuals for whom Anthropometry visit is pending. This includes program as well as general encounter. (Title - Anthropometry details to be collected)
- [x] Count of individuals for whom Substance use visit is pending.

**Comment by Gojo-Taqi** [comment]
The mothers not mapped to household card is not possible.
The other card's logic is ready, but due to a bug, that card has not been included.
Once the bug is resolved, it will be added.
Anything related to substance use or Collect blood sample details, is related to the bug
Link to the bug card given below
https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/949

**Comment by Dinesh2019** [comment]
Moving this card to on hold due to this bug.
https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/960
