### ISSUE TITLE
[IPH] Changes required for Go live

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#28]
- [x] Some individuals have been created with same Individual Id (which is a unique identifier) - need to identify why this has happened - check the attached sheet for reference, refer to ind_individual id column.
https://drive.google.com/drive/u/0/folders/1FWb92jxzdENtIzrGXFIJavP1WK-X3gMM
- [x] Schedule Delivery form after 238 days from LMP (Last menstrual period)
- [x] Register a household, click on Add member. Register a new individual with gender female, is pregnant woman yes. Add a relative to the mother (head of household), select relationship as brother, add new male indiviudal - after adding when user clicks on Save - app throws error "Fatal error - non determinate relationship type" - attaching screenshot at the end.
- [x] Record Child anthropometry encounter showing as an unplanned visit - hide it.
- [x] Mother anthropometry form:
The condition applied for Biceps skinfold reading 1 should also be applicable for Biceps skinfold reading 2.
The condition applied for Triceps skinfold reading 1 should also be applicable for Triceps skinfold reading 2.
The condition applied for Subscapular skinfold reading 1 should also be applied for Subscapular skinfold reading 2.
- [x] The same rules for above field needs to be applied to Child anthropometry encounter as well.
- [x] The rule defined for Serum sample adequate question in Blood sample collection encounter is not working.
- [ ] Upload the bundle on prod and verify the changes.

**Comment by Gojo-Taqi** [comment]
ETC - 5 hrs

**Comment by Gojo-Taqi** [comment]
Record Child anthropometry encounter showing as an unplanned visit - hide it.
For this point, it is not getting shown as unplanned visit, if a visit is planned, that visit is getting shown there

**Comment by Dinesh2019** [comment]
we found a  bug when we register the individual in the individual details we have a field called occupation which is the multi-select field we select an option and click on the next. Again click on previous if we try to edit the occupation filed it is non-editable.(I think it is a prod bug we need to confirm)
Env: UAT
user: dineshg@iphctrith_UAT

https://images.zenhubusercontent.com/538437669/01afec0e-f149-43c1-88f9-521e085c4cd4/record_2023_05_15_19_10_43__1_.mp4

**Comment by utkarshavni** [comment]
@Gojo-Taqi  I dont understand how Child anthropometry is not visible as an unplanned encounter - i was able to see it in my device. The client also shared a screenshot in the evening. Sharing the screenshot here.  @Dinesh2019 can you have a look at this once?
![WhatsApp Image 2023-05-15 at 22.32.44.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/fd869b40-4771-4b03-92fe-8ce9fab869cd)

**Comment by utkarshavni** [comment]
@Gojo-Taqi @Dinesh2019  i have added task for uploading bundle and moving the card to in progress.

**Comment by Gojo-Taqi** [comment]
Moving back to ready as uploading bundle fix is in progress and goes out with the release

**Comment by utkarshavni** [comment]
Closing this card as we have created a new org.
