### ISSUE TITLE
[IPH] Go Live tasks

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#29]
- [x] Create a new organization - Title: "CTRITH IPH"
- [x] User suffix will be @ctrith_iph
- [x] Move bundle from IPH CTRITH UAT to the new org.
- [x] Verify all the changes from the card mentioned below are updated in the new org.
https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/iph-ctrith/28
- [x] Create all the users available in IPH CTRITH org.
- [x] Assign identifiers for the users to generate unique ids.
- [x] Make sure all users are able to login with the credentials.
- [x] Make sure user permissions are working as defined.
- [x] Upload Kannada translations from IPH CTRITH org to the new org.

**Comment by Dinesh2019** [comment]
The rule defined for Serum sample adequate question in Blood sample collection encounter is not working.
serum sample is not displayed 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/d7a20ab6-7b98-43b8-9eec-3b1445c145eb)

**Comment by utkarshavni** [comment]
@Gojo-Taqi  @dinesh2096 

- [x] Make sure delivery form is same as IPH CTRITH org
- [x] Make sure Mother Anthropomtery form is same as IPH CTRITH org
- [x] Make sure Substance use form is same as IPH CTRITH org
