### ISSUE TITLE
Minor UAT changes - 2

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/IPH-CTRITH#31]
Look from row 173
https://docs.google.com/spreadsheets/d/1tuH3xm8X3rlAYgduuM4wDGQTK1KUq5_ate2AjoXCCN4/edit#gid=0

**Comment by Gojo-Taqi** [comment]
Moving this card back to ready as one of the feedback point is unclear, we asked yogesh for his contribution on that point.

**Comment by utkarshavni** [comment]
@dinesh2096 - moving this card to deploy ready since it is tested.
