### ISSUE TITLE
[IPH] Move changes from UAT to prod

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/IPH-CTRITH#33]
Support ticket - https://avni.freshdesk.com/a/tickets/2794

- [x] There is a from element group - "Socio demographic" in form "Substance use Enrolment" on org "IPH CTRITH". This needs to be moved to "CTRITH IPH" prod org.

**Comment by Gojo-Taqi** [comment]
ETC :- 15 mins
Completed in :- 15 mins
