### ISSUE TITLE
[IPH] Freeze unique id once generated

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#38]
**Organizations**
UAT - CTRITH IPH UAT
Prod - CTRITH IPH

**Use case**
An individual can migrate to a different location. While changing the location of the user, the Individual id is updated as it takes the location name in prefix. Since this id is also used offline for blood samples and tracked further, any changes in id will create challenges for the program team in tracking, compiling and analyzing the data. 

**Goal:**
The Individual id should not be modified once generated, irrespective of the changes made on the first registration page.

**Comment by arjunk** [comment]
@utkarshavni we should have a tech lead assigned on this and story should be reviewed before moving further.

**Comment by utkarshavni** [comment]
@salilsamanvay @nupoorkhandelwal @sachsk 
moving this to Tech lead review.
