### ISSUE TITLE
[IPH] Delivery form for mother

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#5]
- [x] Create a general encounter called Delivery, against Individual subject type.
- [x] Encounter Eligibility - Only eligible when individual Registration has Last menstrual period field with answer.
- [x] Hide encounter from "New Forms".
- [x] Schedule encounter on Expected date of delivery - the date is auto calculated in Registration form. 
- [x] Overdue date should be 15 days after the due date.
- [x] Form requirements: 
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=1198905690

**Comment by Gojo-Taqi** [comment]
Expected time of completion :- 25 mins
Time taken to complete :- 30 mins

**Comment by AchalaBelokar** [comment]
Date of Delivery should not be in future .
Currently  it is showing that need a validation

**Comment by utkarshavni** [comment]
- [x] Create a household, add head of household. Now add wife of household by add member - when wife is registered with LMP and other details given, the delivery form is not scheduled. When i create individual separately with above details, then Delivery form is scheduled.  Beneficiary where this can be checked - "Sample Mother"  @Gojo-Taqi

**Comment by AchalaBelokar** [comment]
- [x] I fill the delivery encounter before schedule date ,

the schedule date is 25th jan 2023. but I filled it 10 jan 2023 . still dilvery encounter is showing planned visit. pls see the individual  Mother Teresa.
