### ISSUE TITLE
[IPH] Mother program enrolment and exit

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#6]
Once mother is eligible for the study and follow-up and provides consent, she will be enrolled into Mother program.

- [x] Create a program called Mother.
- [x] Program enrollment eligibility - When in Delivery encounter, "Are any of these conditions applicable to mother and child" has any answer except None, only then the Program option should be visible for user to enroll the woman.
- [x] Enrollment form requirements:
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=194916367
- While enrolling mother, field investigator asks details about the obstetrics history of mother and questions about symptoms of post natal depression and social support available.
- [x] Program Exit form:
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=918524599

**Comment by Gojo-Taqi** [comment]
Estimated time of completion :- 1hr
Completed in :- 1.5 hr

**Comment by AchalaBelokar** [comment]
Over the last 2 weeks, how often have you been bothered by any of the following problems: its a non mandatory .

**Comment by Gojo-Taqi** [comment]
Removed the question "Obstetrics history of mother" and replacing with the 5 new ones(row 5-9).
