### ISSUE TITLE
[IPH] Record mother Anthropomtery details

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#8]
- [x] Create a program encounter named "Record mother anthropometry details" for Mother program against subject Individual.
- [x] Schedule the encounter after the enrollment on the same date as of enrollment.
- [x] Schedule further visits as mentioned. One visit will only be scheduled after the completion of previous one.
- 2nd - Three months after the enrollment.
- 3rd - Six months after the enrollment.
- 4th - 1 year after the enrollment.
- 5th - 2 year after the enrollment. This will be the last scheduled visit.
- On Cancelling a visit, the same visit need to be scheduled after a week, Overdue date to be three days afterwards.
- [x] Form requirements:
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=583276325

**Comment by Gojo-Taqi** [comment]
Time taken to complete this card :- 2.5hrs
Estimated time of completion :- 2hrs
