### ISSUE TITLE
[IPH] Blood sample collection for Mother

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#9]
- [x] Create a program encounter named "Collect blood sample details" for Mother program against the Subject Individual.
- [x] This visit will be scheduled on the same date as enrollment after enrollment is done and overdue will be date after two weeks.
- [x] Further scheduling will happen as given below:
- 2nd visit - 12 months after enrollment.
- 3rd visit - 2 years after enrollment. This will be last sample collection.
- [x] Form requirements:
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=651233342   (Only include fields for which "When to show" column shows Mother.
- [x] On cancelling visit, the same should be scheduled again after a week, with overdue after 3 days after a week.

**Comment by AchalaBelokar** [comment]
- [ ] what happen when we cancel this visit  requirement is missing

**Comment by utkarshavni** [comment]
@AchalaBelokar @Gojo-Taqi - Updated requirement for cancelling visit.

**Comment by utkarshavni** [comment]
@Gojo-Taqi  @AchalaBelokar  - Change in visit scheduling logic, so moving this card to ready. Change has been updated in card and unticked that task.

**Comment by AchalaBelokar** [comment]
- [ ] 2nd visit - 12 months after enrollment. unable to generate visit logic

**Comment by Gojo-Taqi** [comment]
@AchalaBelokar The logic is working fine, can you test again pls
